[package]
name = "pingbot"
version = "0.1.0"
authors = ["you06 <you1474600@gmail.com>"]
edition = "2018"

[dependencies]
github-rs = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { git = "https://github.com/clap-rs/clap/" }
toml = "0.5"
