# slack
# OAuth access token, user token scopes are required.
tidb-slack-token = "slack-token"
tikv-slack-token = "xxx"
slack-channel = "slack-channel"

# github
github-token = "github-token"
repos = ["you06/pingbot"]
filter-labels = [
  "repo:filter-label-1",
  "repo:filter-label-2",
  "repo3"
]

# discourse
discourse-base-url = "https://asktug.com"
# categories to be searched
# check it out from {discourse-base-url}/categories.json
discourse-categories = ["TiDB 用户问答", "TiDB 开发者"]
# for the users don't have name with `PingCAP` suffix, list them here
discourse-members = [
  "you06"
]

[[sigs]]
name="transaction"
labels=["repo:component/coprocessor","rep3"]
slack-channel="xxx"

[[sigs]]
name="ddl"
labels=["repo:component/parser","repo4"]
slack-channel='xxxxaaa'