# github
github-token = ""
repos = ["you06/pingbot"]

# discourse
discourse-base-url = "https://asktug.com"
# categories to be searched
# check it out from {discourse-base-url}/categories.json
discourse-categories = ["TiDB 用户问答", "TiDB 开发者"]
# for some users don't have name with `PingCAP` suffix, list them here
discourse-members = []
