# slack
# OAuth access token, user token scopes are required.
tidb-slack-token = "slack-token"
tikv-slack-token = "xxx"
slack-channel = "slack-channel"

# github
github-token = "github-token"
repos = ["you06/pingbot"]
filter-labels = [
  "filter-label-1",
  "filter-label-2"
]

# discourse
discourse-base-url = "https://asktug.com"
# categories to be searched
# check it out from {discourse-base-url}/categories.json
discourse-categories = ["TiDB 用户问答", "TiDB 开发者"]
# for the users don't have name with `PingCAP` suffix, list them here
discourse-members = [
  "you06"
]

[[sigs]]
name="transaction"
labels=["component/coprocessor","label2"]
slack-channel="xxx"

[[sigs]]
name="ddl"
labels=["component/parser","lable2"]
slack-channel='xxxxaaa'